
import { ContextProvider } from "@/components/Context/context";
import "./globals.css";
import "animate.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Shippers' Council Bangladesh",
  description: "Generated by create next app",
};
const RootLayout = ({ children }) => {

  return (
    <html lang="en">
       <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Quattrocento+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-body">
        <div id="modal-root"></div> {/* Container for modals */}
        <ContextProvider>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
          
        </ContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
