import { ContextProvider } from "@/components/Context/context";
import "./globals.css";
import "animate.css";

import { Poppins, Quattrocento_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Shippers' Council Bangladesh",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const quattrocentoSans = Quattrocento_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${quattrocentoSans.className}`}>
        <ContextProvider>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
